### PR TITLE
 Added new tab to display JavaScript client method for plone 

### PR DESCRIPTION
**Pull request by datakurre**

### CODE REVIEW

**Comment by sneridagh** [comment]
@datakurre @stevepiercy We are trying to resurrect this with @robgietema , we were wondering which would be the next step in order to be able to define the contents of the JavaScript usage.

This is how the tab would have to look like:

```ts
import PloneClient from '@plone/client';
const cli = PloneClient.initialize({apiPath: 'http://nohost/plone'});
const { data, status } = cli.getContent({path: '/', expanders: ['breadcrumbs', 'navigation']})
```

Would it be ok to add another parameter like `:request:`, let's say `:javascript:` that points to a file where we have that information? Could you give us a few pointers how to achieve that? Thanks!

**Comment by datakurre** [comment]
Please, provide a few examples with the required raw http request (source) and the desired JS outcome (example). I should be able to check this in the evening.

**Comment by sneridagh** [comment]
@datakurre The GET content, for example, which is:

https://plonerestapi.readthedocs.io/en/latest/usage/content.html#reading-a-resource-with-get

```
GET /plone/folder/my-document?expand=breadcrumbs,navigation HTTP/1.1
Accept: application/json
Authorization: Basic YWRtaW46c2VjcmV0
```

The JS tab will show:

```
import PloneClient from '@plone/client';
const cli = PloneClient.initialize({apiPath: 'http://nohost/plone'});
const { data, status } = cli.getContent({path: '/plone/folder/my-document', expanders: ['breadcrumbs', 'navigation']})
```

We've been talking with @robgietema and we concluded that trying to parse the HTTP request will be too much... that's why I was mentioning that doing it by hand would be still ok, by providing a file with the content of the tab... I guess that at some point, given the nature of the arguments required by the endpoints, that might be tricky. Of course that anything better will be appreciated! We also said that we might provide the arguments with `:path:` hints too...

**Comment by datakurre** [comment]
@sneridagh Thanks you. I think I now got this. I'll see how far I can get.

**Comment by stevepiercy** [comment]
There's also this issue with a preview:

https://github.com/collective/sphinxcontrib-httpexample/issues/90#issuecomment-1932562540

**Comment by datakurre** [comment]
I didn’t get it ready yet, sorry, because I could not resist to finally drop Python 2 and deprecated APIs. 🙈 Will continue after Friday

**Comment by stevepiercy** [comment]
@datakurre is this what you seek?

- https://github.com/collective/sphinxcontrib-httpexample/issues/90#issuecomment-1933913795
- https://plone-client.readthedocs.io/en/latest/actions/aliases.html#add-aliases-for-multiple-pages
- https://github.com/plone/volto/tree/main/packages/client/src/restapi/aliases

Sorry, I'm not exactly clear, so I'm making a guess.

**Comment by sneridagh** [comment]
@datakurre We did a bit of refinement of the names of the API functions in the JS API these days, so they might be "predictable", however, there's no 100% sure that they will be, however, let's try, we can change them still, since we are in the first alpha.

Here you have a variety of examples:

https://plonerestapi.readthedocs.io/en/latest/usage/content.html#updating-a-resource-with-patch

name: `updateContent`
method: `PATCH`

```
PATCH /plone/folder/my-document HTTP/1.1
Accept: application/json
Authorization: Basic YWRtaW46c2VjcmV0
Content-Type: application/json

{
    "title": "My New Document Title"
}
```

https://plonerestapi.readthedocs.io/en/latest/usage/content.html#removing-a-resource-with-delete

name: `deleteContent`
method: `DELETE`

```
DELETE /plone/folder/my-document HTTP/1.1
Accept: application/json
Authorization: Basic YWRtaW46c2VjcmV0
```

https://plonerestapi.readthedocs.io/en/latest/endpoints/email-send.html

name: `emailSend` (we can amend this one)
method: `POST`

```
POST http://localhost:8080/Plone/@email-send
Accept: application/json
Content-Type: application/json

{
  "name": "John Doe",
  "from": "john@doe.com",
  "to": "jane@doe.com",
  "subject": "Hello!",
  "message": "Just want to say hi."
}
```

https://plonerestapi.readthedocs.io/en/latest/usage/authentication.html#json-web-tokens-jwt

name: `login`
method: `POST`

```
POST /plone/@login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "login": "admin",
    "password": "secret"
}
```

For more examples, of course, you can go to: https://plonerestapi.readthedocs.io/

And where the API lives nowadays: https://github.com/plone/volto/tree/main/packages/client

Thanks a lot Asko!!

**Comment by robgietema** [comment]
@datakurre Since this is a normal api and not an restapi some things are indeed different. I think about 95% can be generated automatically but the 5% is where the issues are. Some examples:

The rest api uses http calls so you have get, post, patch, delete. This can be converted to get, create, update and delete (GET content -> getContent, DELETE content -> deleteContent) etc. But some endpoints don't have that "method" in the api call, for example "GET search" will be just "search" since "getSearch" doesn't make sense. Same with login, send email and email notification.

Another example is querystring search. Here we have a GET and a POST variant. But since this is an implementation detail and if you implement the client without http calls it will be just "querystringsearch" without the get and post before that. (currently the method is passed as a parameter).

Another example are the calls which are "global". For example you can call the get aliases call on the root of the site or on a content object. The http request looks the same but they return different data. The get aliases on the root returns all the aliases in the whole site and the get aliases on a content object just the items on that object. So in the api they are called getAllAliases and getAliases.

You can find a full list of all the method at: https://github.com/plone/volto/blob/main/packages/client/src/client.ts

**Comment by datakurre** [comment]
Thanks for the examples and references. I'll try to return to this this evening.

For me, it still sounds that the possibility to maintain "custom example builder" in the docs' conf.py, would allow the necessary hacks for the special case.

For methods without REST API version, maybe their examples could be written without this add on.

> But some endpoints don't have that "method" in the api call, for example "GET search" will be just "search" since "getSearch" doesn't make sense. Same with login, send email and email notification.

But these could be detected from URL and handled as special case in the custom example builder?

> But since this is an implementation detail and if you implement the client without http calls it will be just "querystringsearch" without the get and post before that. (currently the method is passed as a parameter).

So, having both GET and POST could result in redundant JavaScript examples? But would that be a real problem?

> The get aliases on the root returns all the aliases in the whole site and the get aliases on a content object just the items on that object. So in the api they are called getAllAliases and getAliases.

I guess, it would be OK for the custom builder to assume that path with just one content part (`/plone`) would be site root the rest content objects.

Well, this get more concrete, when I do the initial reimplementation.

**Comment by datakurre** [comment]
@sneridagh Am I on the right path here https://sphinxcontrib-httpexample.readthedocs.io/en/py3/custom.html

**Comment by sneridagh** [comment]
@datakurre By looking at the examples in that URL, I think you do!!

**Pull request merged**
