### PR TITLE
Support non-json requests.

### LINKED ISSUE #11: Only application/json is supported
I'm working on examples that issue PATCH requests using `Content-Type: application/offset+octet-stream`.
I'm a bit confused on why there is an explicit check for `application/json` in here?

### PR DESCRIPTION
**Pull request by jaroel**
Closes #11

### CODE REVIEW

**Comment by jaroel** [comment]
@datakurre any idea why the tests are failing only on travis, works-on-my-machine ?

**Comment by datakurre** [comment]
@jaroel Don't worry. I'll check this today.

**Comment by jaroel** [comment]
@datakurre awesome, thank you!

**Comment by datakurre** [comment]
The tests only failed on Python 3 (because bytes were printed with b''). There was issue in Python 2 build, which did hide the issue. (The build did first properly run tests for Python 2, but then also on Python 3 which failed.)

I'm a bit sorry for the nix based setup here, but I want to learn it more somewhere and it was the part of fun in this project.

**Pull request merged**
